version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: '[actions] chore'
    labels:
      - github-actions
    target-branch: parent

  - package-ecosystem: pub
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: '[deps] chore'
    labels:
      - pub
    target-branch: parent
    versioning-strategy: widen

  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: '[devcontainer] chore'
    labels:
      - dev-container
    target-branch: parent
