name: dart

on:
  push:
    branches: parent
    paths:
      - '**.dart'
      - '.github/workflows/*.yaml'
      - analysis_options.yaml
      - pubspec.yaml

jobs:
  format: 
    name: format
    runs-on: ubuntu-latest
    container: dart
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Check whether code is formatted
        run: dart format . -o none --set-exit-if-changed --follow-links

  analyze: 
    name: analyze
    runs-on: ubuntu-latest
    needs: format
    strategy:
      fail-fast: false
      matrix:
        version:
          - stable
          - 3.0.0
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.version }}

      - name: Enable commented lints (if supported)
        run: .github/scripts/enable_commented_lints.dart

      - name: Install dependencies
        run: dart pub get -v

      - name: Analyze code
        run: dart analyze --fatal-infos
